- name: web server configuration
  hosts: web
  become: yes
  vars_prompt:
    - name: CATALOGUE_HOST
      prompt: Enter CATALOGUE domain/IP
      private: false
    - name: USER_HOST
      prompt: Enter USER domain/IP
      private: false
    - name: CART_HOST
      prompt: Enter CART domain/IP
      private: false
    - name: SHIPPING_HOST
      prompt: Enter SHIPPING domain/IP
      private: false
    - name: PAYMENT_HOST
      prompt: Enter PAYMENT domain/IP
      private: false
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Remove default web content
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: Download web application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: Unarchive web application
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: Copy reverse proxy configuration
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: Replace CATALOGUE domain name/IP
    ansible.builtin.replace:
      path: /etc/nginx/default.d/roboshop.conf
      regexp: '<catalogue-ip>'
      replace: '{{ CATALOGUE_HOST }}'

  - name: Replace USER domain name/IP
    ansible.builtin.replace:
      path: /etc/nginx/default.d/roboshop.conf
      regexp: '<user-ip>'
      replace: '{{ USER_HOST }}'

  - name: Replace CART domain name/IP
    ansible.builtin.replace:
      path: /etc/nginx/default.d/roboshop.conf
      regexp: '<cart-ip>'
      replace: '{{ CART_HOST }}'

  - name: Replace SHIPPING domain name/IP
    ansible.builtin.replace:
      path: /etc/nginx/default.d/roboshop.conf
      regexp: '<shipping-ip>'
      replace: '{{ SHIPPING_HOST }}'

  - name: Replace PAYMENT domain name/IP
    ansible.builtin.replace:
      path: /etc/nginx/default.d/roboshop.conf
      regexp: '<payment-ip>'
      replace: '{{ PAYMENT_HOST }}'

  - name: Start and Enable service
    ansible.builtin.systemd_service:
      name: nginx
      enabled: yes
      state: restarted
